### ISSUE TITLE
Suspending/Unsuspending 

### ISSUE THREAD

**Issue by DoctorToBeIn23** [Arthur-Milchior/anki-browser-for-note#1]
Is there any way you can make it so that you can have an option in the config to where you can have it when you unsuspend any part of the note that it unsuspendeds all of the cards contained in the note?

**Comment by Arthur-Milchior** [comment]
Seems possible yeah

**Comment by DoctorToBeIn23** [comment]
Btw hope your doing well and killing it at your new job!

**Comment by Arthur-Milchior** [comment]
This is now configurable. By default it follows your idea. I am surprised I didn't already implemented it. Was probably done in Advanced browser, but then the feature got into its own add-on and then I totally forgot it.

I currently have a policy not to do any comment about the job itself, appart that I have got one, so excuse me for not answering, but thanks for your hope

**Comment by DoctorToBeIn23** [comment]
Thanks for doing this we all appreciate you!
