### ISSUE TITLE
Why would I need this add-on, if I could just add "card:1" to my search string?

### ISSUE THREAD

**Issue by Andrej-Adamenko** [Arthur-Milchior/anki-browser-for-note#5]

**Comment by Arthur-Milchior** [comment]
You're of course free not to use it. I'm not forcing anyone. If you feel like it's better for you, just do it.

Personally, it would not work for plenty of reason:
* I've siblings (multiple cards of a same note) in multiple deck. Let's take decks D1 and D2. A note N with card C1 and C2 in deck D1 and D2 respectively. Let's say I'm searching for N in deck D2. If I restrict "card:1", it will not return any result.
* I've complex note type. Sometime the first card is not actually generated. In this case, the note without card 1 will never be shown in any search result with card:1

**Comment by Andrej-Adamenko** [comment]
Thank you for explanation. Now I see why the addon is useful.
