### ISSUE TITLE
Please update for compatability with latest anki versions

### ISSUE THREAD

**Issue by xy3xx** [Arthur-Milchior/anki-browser-for-note#7]
Hi, this add-on looks like a really helpful feature that I would like to use with my Anki decks. In fact, it should be a built-in feature of Anki.  I am sure you are quite busy, but I think the Anki community would also benefit if you could update it for compatibility with the latest Anki version.  Thanks for your hard word and coding!

**Comment by Arthur-Milchior** [comment]
It has been a built-in feature for quite some versions now, so the add-on became useless
